services:
  pyai:
    image: pyai
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    volumes:
      - ./tmp:/home/manav/Documents/pyai/tmp
    restart: unless-stopped

