services:
  pyai:
    image: pyai
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    volumes:
      - /home/manav/Documents/pyai/prod/tmp:/app/tmp
      - /home/manav/Documents/pyai/prod/log:/app/log
    restart: unless-stopped

